### ISSUE TITLE
Documentation: FreshRSS FilterTitle: How is this different from in-built mark article as read in freshrss?

### ISSUE THREAD

**Issue by lamyergeier** [cn-tools/cntools_FreshRssExtensions#13]
Freshrss has native feature to mark article as read based on the keywords: [[Filtering articles](https://freshrss.github.io/FreshRSS/en/users/10_filter.html)](https://freshrss.github.io/FreshRSS/en/users/10_filter.html)

How is this different than that? Does it support regex?

**Comment by cn-tools** [comment]
With this extension the new feed entry will NOT be added into your FreshRSS database / instance. The equivalent entry is  fully blocked.

At the moment it's string compare only.
Maybe comes regex compare in the future.

**Comment by lamyergeier** [comment]
Regex support can solve this issue: [[Feature Hide/delete articles using non latin script · Issue #6144 · FreshRSS/FreshRSS](https://github.com/FreshRSS/FreshRSS/issues/6144)](https://github.com/FreshRSS/FreshRSS/issues/6144)

**Comment by cn-tools** [comment]
@lamyergeier feel free to try the extension FilterTitle with now implemented regex

**Comment by lamyergeier** [comment]
Can I do as follows

```
[sS]ponsor
[aA]dvertisement
[sS]horts?
```

Is it possible to specify case insensitvity like

```
/sponsor/i
/advertisement/i
/shorts?/i
```

What about pattern with space

```
North Korea
```

Could you suggest regex to ignore non-latin scripts (example, Chinese, Japanese, Korean, Arabic, Thai, Hindi, Tamil, Kannada, Telugu languages)?

-----

I am not sure about the syntax.

**Comment by cn-tools** [comment]
i reworked the plug in, so update your installation please.

you can now define how the check result should be used. use as block or release.

in your case i think you have to use `release`and regex `/\p{Latin}/i`

**Comment by lamyergeier** [comment]
Could you please say what is meant by  block, release and exam type?

**Comment by cn-tools** [comment]
I think I should define a clearer text 🤪

The exam type determines how the result of the check is used.
This allows you to specify that the keywords are applied as a blacklist or whitelist to the title of the feed entry.

In your issue [6144](https://github.com/FreshRSS/FreshRSS/issues/6144) you say that you wants feed entries with Latin chars in title only.
And in this case i would define `release` and as keyword `/\p{Latin}/i`

**Comment by lamyergeier** [comment]
May be we should have separate black and white lists?

**Comment by lamyergeier** [comment]
So if I add `/\p{Latin}/i` in whitelist, then feeds with non latin charaters will get automatically deleted? 

Also may I request if its possible to add an option to either delete or mark as read based on the filter.

**Comment by lamyergeier** [comment]
> I will try to provide an option to set the new feed entry to be added to the database as read

may be its useful to give this option separately for whitelist and blacklist for more granular control

**Comment by lamyergeier** [comment]
May be its also useful to tag the filtered and read feeds as *FilterTitle* to indicate that those feeds were marked read automatically by the extension.

**Comment by cn-tools** [comment]
@lamyergeier checkbox for "mark as read" is available in the actual version
i'm waiting for your response

**Comment by lamyergeier** [comment]
@cn-tools  I uodated the extension, enabled this setting, would confirm that it works , if I see non latin feeds marked read.

**Comment by lamyergeier** [comment]
@cn-tools  Issue: checkbox selection does not persist in GUI!

**Comment by cn-tools** [comment]
@lamyergeier ah sh*t - sorry

i used a wrong save name for data of the checkbox.

update once again please.
you must set the checkbox new and save it.

waiting for your answer

**Comment by lamyergeier** [comment]
Title with punctuation marks getting ignored!

Solution: include every supported property code ([PHP: Unicode character properties - Manual](https://www.php.net/manual/en/regexp.reference.unicode.php))

example:

![image](https://github.com/cn-tools/cntools_FreshRssExtensions/assets/42092626/e94556c2-f758-4dab-9484-d047597f91db)

**Comment by cn-tools** [comment]
could you send me your regex please, because if you allow i would like to add it to examples

**Comment by lamyergeier** [comment]
Can you check if the whitelist is working? I did the following:

```php
<?php
$String="தமிழ் அரிச்சுவடி";
if (preg_match("/\p{Latin}/i", $String)) {
    echo "A match was found in $String.\n";
} else {
    echo "A match was not found in $String.\n";
}
```

returns,


````
A match was found in தமிழ் அரிச்சுவடி.
```

**Comment by cn-tools** [comment]
here is a regex provided as you are searching for: [https://stackoverflow.com/a/70533736](https://stackoverflow.com/a/70533736)
