### ISSUE TITLE
YouTube2RssFeed breaks FreshRSS

### ISSUE THREAD

**Issue by G-Huber** [cn-tools/cntools_FreshRssExtensions#18]
I just tried updating YouTube2RssFeed.
It seems something broke with the latest commit a8bf70a156682c4340be4b2d1b7bbddf94db876a.

After copying the extension to my ./extensions folder FreshRSS only ever displays a blank page.
Deleting the extension fixes this issue.

For now I just switched to the previous version - which works.

Using PHP 7.4.33, lighttpd and FresRSS 1.23.1
If there is further detail I can provide, I'll gladly do so - just tell me what's needed.

**Comment by G-Huber** [comment]
Due to my hosting provider I'm unfortunately stuck with FreshRSS being directly installed on Debian 11.
I'm not comfortable enough with PHP to update to a version not supported by my distribution.

As for logs: FreshRSS logs are empty, lighttpd last entry is about it's last restart and /var/log/php7.4-fpm.log only shows
`[06-May-2024 17:09:42] WARNING: [pool www] server reached pm.max_children setting (5), consider raising it`
which I also wouldn't consider related.

Are there log files I missed? Do I need to increase loglevels?

**Comment by cn-tools** [comment]
it looks like an incompatibility with php v7.4
i will check and fix it

**Comment by cn-tools** [comment]
could you try the actual version please?

**Comment by G-Huber** [comment]
The current version no longer causes the blank page issue :)

FreshRSS properly shows up and the extensions settings page was available.

Thank you very much!
