### ISSUE TITLE
YouTubeChannel2RssFeed不显示内嵌视频

### ISSUE THREAD

**Issue by jxjxjhjh** [cn-tools/cntools_FreshRssExtensions#2]
使用PeerTube Video Feed扩展则正常。

**Comment by cn-tools** [comment]
thx4msg

I hope the online translater did his jop right :)

If you like, you can use "YouTube/PeerVideo" instead of mine plug-in.
Is the availability of my plug-in an issue?

**Comment by jxjxjhjh** [comment]
YouTubeChannel2RssFeed

![](https://i0.hdslb.com/bfs/album/c4c847af79e2210a7f8191e7187d1332497d9109.jpg)

NO VIDEO


PeerTube Video Feed

![](https://i0.hdslb.com/bfs/album/531b1b9bcb26a0e11536fe0d7805e21d292b1ac8.jpg)

YES PLAY VIDEO

**Comment by cn-tools** [comment]
At this time this plugin has no functionality about embedded videos like "YouTube/PeerVideo".

**Comment by cn-tools** [comment]
In addition to my plug-in you can use [freshrss-invidious](https://github.com/Korbak/freshrss-invidious) from [Korbak](https://github.com/Korbak) to receive inline videos as you like
