### ISSUE TITLE
YouTubeChannel2RssFeed does not exist in configuration

### ISSUE THREAD

**Issue by roughnecks** [cn-tools/cntools_FreshRssExtensions#26]
Hello,
just updated the extension but my FreshRSS logs tell me that "YouTubeChannel2RssFeed does not exist in configuration" every time I open its settings.

I don't know what configuration doesn't exist.

Thanks

**Comment by cn-tools** [comment]
i'm sorry for the late answer!

may i have mor infos about your problem?
I don't write this text into log files and i tested the current version without any content inside the config file and it works

**Comment by cn-tools** [comment]
please try the version of [this branch](https://github.com/cn-tools/cntools_FreshRssExtensions/tree/user_conf2userConf)

**Comment by roughnecks** [comment]
I just tried, but..

![image](https://github.com/user-attachments/assets/cde26bda-614b-4202-983f-61ce44753aa3)

Is the version alright?

![image](https://github.com/user-attachments/assets/4c11e828-dfa3-49bb-bb5d-0fffc1925bc6)
