### ISSUE TITLE
FreshRSS YouTubeChannel2RssFeed goes to blank page after save

### ISSUE THREAD

**Issue by tonyrulez** [cn-tools/cntools_FreshRssExtensions#28]
**System informatrion**
FreshRSS: 1.20.0
YouTubeChannel2RssFeed: 0.6.1

**Reproduction**
Install extension
Use following parameters:
![kép](https://github.com/user-attachments/assets/d1cf2c69-01e9-4075-ae02-838a6a3368f2)

After hitting submit, web page gets redirected to http://FRESHRSS_URL/i/?c=extension&a=configure&e=YouTubeChannel2RssFeed which is an empty page.
Manually reopening FreshRSS Extension page shows that the parameters were not saved for the extension.

**Comment by cn-tools** [comment]
please try the version of the [this branch](https://github.com/cn-tools/cntools_FreshRssExtensions/tree/user_conf2userConf)
