### ISSUE TITLE
xExtension-SendToMyJD2: issue with special characters in the password of myJDownloader2 account

### ISSUE THREAD

**Issue by oshri-almog** [cn-tools/cntools_FreshRssExtensions#31]
A little bug: you cannot use this extension if your myJDownloader2 account password is with special characters, like: "eH%hOxx17i&t9C"

**Comment by cn-tools** [comment]
it looks like that the char "&" makes problems, because in the save process of the params this char will be transferd into "&amp!".

i will have a look
