### ISSUE TITLE
Doesnt Block Shorts

### ISSUE THREAD

**Issue by NilsLeo** [cn-tools/cntools_FreshRssExtensions#37]
Hey, thx for making this

Unofrtunately, this won't block shorts as expected in  my case

My Settings:

![CleanShot 2024-11-27 at 00 25 43@2x](https://github.com/user-attachments/assets/d05bff8c-d573-4d86-b16d-58706d49d9a3)

My Feed

![CleanShot 2024-11-27 at 00 28 26@2x](https://github.com/user-attachments/assets/c0506aa3-a1df-4a1c-b505-34cba5bc7cae)

Settings for this Feed

![CleanShot 2024-11-27 at 00 37 06@2x](https://github.com/user-attachments/assets/ef95be41-cfc5-4ed9-acb1-d9c523a7547d)

As you can see the short wasnt blocked despite being  < 120 seconds. Any idea what could be causing this?

**Comment by glottisfaun0000** [comment]
Looks to me like you didn't enter a URL for the yt-operational-api

**Comment by NilsLeo** [comment]
Yup that seems to have done it. My bad
