### ISSUE TITLE
Filtering away Youtube Shorts?

### ISSUE THREAD

**Issue by krusty4president** [cn-tools/cntools_FreshRssExtensions#8]
Hi. I am using it with my freshrss installation. Is it possible to filter out Youtube shorts with this extension?

**Comment by cn-tools** [comment]
this plug in is changing the url of the added feed only yet and doesn't do any interaction with feed entries.

but i'll take a look if i can fulfill your wish.

**Comment by krusty4president** [comment]
That would be so helpful both to me and the community. Unfortunately som channels just bloat the content with so many YT Shorts.

**Comment by colinstu12** [comment]
Agreed, that would be useful

**Comment by cn-tools** [comment]
Hello @krusty4president and @colinstu12 

a few seconds ago i checked in a alpha version to detect youtube shorts.

Please test it and i'm happy to read your feedback.

**Comment by i300220** [comment]
@cn-tools Hi,  Installed, however I cannot figure out how to configure it.

**Comment by colinstu12** [comment]
Thanks @cn-tools 
Was this addon required previously to import YT channels? I was already able to just put the channel's URL into the add feed screen without the need of addon nor this API docker for [YouTube-operational-API].

**Comment by i300220** [comment]
Shorts are now marked as read, per the extension configuration.  Works perfectly well.  Thank you so much @cn-tools !

Does not log though.  Might be me, not the extension.  All that is logged here from FreshRss is the SimplePie messages.  Found nothing in the GUI nor in the config files to enable logging with Minz_Log

**Comment by cn-tools** [comment]
THX @i300220 for the positive answer!

Do you see any LOG message on LOG page inside the settings of FreshRSS?

**Comment by i300220** [comment]
> Do you see any LOG message on LOG page inside the settings of FreshRSS?

![Capture d’écran du 2024-05-12 12-20-41](https://github.com/cn-tools/cntools_FreshRssExtensions/assets/15702355/630cea8f-4f83-43e5-8bf3-6b6ea065ac1b)

I do, but none related to this extension.

Thanks!

**Comment by i300220** [comment]
Arrgh!  They're now making 20 second videos that aren't technically shorts e.g.

https://www.youtube.com/watch?v=lox2ZemF3HI  -> 200
https://www.youtube.com/shorts/lox2ZemF3HI -> 303 redirect to https://www.youtube.com/watch?v=lox2ZemF3HI

**Comment by cn-tools** [comment]
grrrrrr 🫣

i will have a look, but i think this should be checked and fixed (if iths possible) by the development team of the third-party software

**Comment by i300220** [comment]
Makes sense.  I had a look at the 3rd party code.

This would determine the duration of the same video as above in seconds.

https://yt.lemnoslife.com/videos?part=contentDetails&id=lox2ZemF3HI

```
{
    "kind": "youtube#videoListResponse",
    "etag": "NotImplemented",
    "items": [
        {
            "kind": "youtube#video",
            "etag": "NotImplemented",
            "id": "lox2ZemF3HI",
            "contentDetails": {
                "duration": 20
            }
        }
    ]
}
```

One could check the duration and if it's less than 60 seconds, decide  a short is therefore available  whether there is one or not.

Here, you kill 2 birds with 1 stone: 

https://yt.lemnoslife.com/videos?part=contentDetails,short&id=lox2ZemF3HI

```
{
    "kind": "youtube#videoListResponse",
    "etag": "NotImplemented",
    "items": [
        {
            "kind": "youtube#video",
            "etag": "NotImplemented",
            "id": "lox2ZemF3HI",
            "contentDetails": {
                "duration": 20
            },
            "short": {
                "available": false
            }
        }
    ]
}
```

If you prefer I submit it to the 3rd party, let me know.

Best!

**Comment by cn-tools** [comment]
Your shot on two birds looks like a really good way and base. 👍 

I will have a look in the next few days.
Thx for the DIFF file!

Best!

**Comment by i300220** [comment]
Hi,

Gladly.

Installed.  Duration set to 5 minutes to be certain to intercept some files.  Will reset to 60 seconds if all goes well.  Shorts by duration are very uncommon.

Thanks a lot!

**Comment by i300220** [comment]
Tested with shorts, shorts by duration and regular videos and, everything is as expected.  Best regards.

**Comment by i300220** [comment]
Tested all 3 cases, shorts, shorts by duration( 5 mins and 60 secs), and normal length videos and everything is working as expected.  Good work!

**Comment by luckycold** [comment]
I hope this isn't me just bringing this up for nothing. But it seems to be the case that this is applied to *all* YouTube videos with RSS. Is there a way to make it where it can be enabled dependent on the channel?

**Comment by i300220** [comment]
``I noticed zero youtube videos in my feeds for a few weeks.

Testing https://yt.lemnoslife.com/videos?part=contentDetails,short&id=lox2ZemF3HI showed contentDetails duration = 0 therefore all videos are being rejected.

Just documenting the issue before I go to lemnoslife to determine what has changed.

I think it would be prudent for now to test if the duration == 0 near lines 251-252 and if so abort.


```
                                        $extraLogTxt = '('.strval($ytDuration).'<'.strval($shortDuration).')';
                                        if ($ytDuration < $shortDuration && $ytDuration > 0) {
                                            Minz_Log::debug('YouTubeChannel2RssFeed-isShort: THIS IS A SHORT (by duration)'.$extraLogTxt);
                                            $result = true;
                                        }

```

I am currently testing the code.


Best!
